name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          script: cd ${{ vars.PROD_PATH }}
            && su ${{ secrets.USER_NAME }}
            && git checkout master
            && git reset --hard
            && git pull
            && rm composer.lock
            && cp deploy/queue-worker.conf /etc/supervisor/conf.d/${{ secrets.USER_NAME }}.conf
            && supervisorctl reread
            && service supervisor restart
            && chown ${{ secrets.USER_NAME }}:${{ secrets.USER_NAME }} . -R
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          port: 22
          script: cd ${{ vars.PROD_PATH }}
            && php -v
            && /opt/php81/bin/php /usr/local/bin/composer install --ignore-platform-req=ext-http --ignore-platform-req=ext-dom
            && /opt/php81/bin/php artisan key:generate
            && /opt/php81/bin/php artisan migrate
            && /opt/php81/bin/php artisan optimize
            && /opt/php81/bin/php artisan cache:clear
            && /opt/php81/bin/php artisan telegram:delete-webhook
            && /opt/php81/bin/php artisan telegram:set-webhook
            && truncate -s 0 ${{ vars.PROD_PATH }}/storage/logs/laravel.log
            && truncate -s 0 ${{ vars.PROD_PATH }}/storage/logs/queue.log




